{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import *\n",
    "from tkinter import messagebox"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "window=tk.Tk()\n",
    "window.title(\"Handwritten digit recognition\")\n",
    "\n",
    "l1=tk.Label(window,text=\"Digit\",font=('Algerian',20))\n",
    "l1.place(x=5,y=0)\n",
    "\n",
    "t1=tk.Entry(window,width=20, border=5)\n",
    "t1.place(x=150, y=0)\n",
    "\n",
    "def screen_capture():\n",
    "    import pyscreenshot as ImageGrab\n",
    "    import time\n",
    "    import os\n",
    "    os.startfile(\"C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Accessories/Paint\")\n",
    "    s1=t1.get()\n",
    "    os.chdir(\"E:/DS and ML/Untitled Folder/Untitled Folder/captured_images\")\n",
    "    os.mkdir(s1)\n",
    "    os.chdir(\"E:/DS and ML/Untitled Folder/Untitled Folder/\")\n",
    "\n",
    "    images_folder=\"captured_images/\"+s1+\"/\"\n",
    "    time.sleep(15)\n",
    "    for i in range(0,5):\n",
    "        time.sleep(8)\n",
    "        im=ImageGrab.grab(bbox=(60,170,400,550)) #x1,y1,x2,y2\n",
    "        print(\"saved......\",i)\n",
    "        im.save(images_folder+str(i)+'.png')\n",
    "        print(\"clear screen now and redraw now........\")\n",
    "    messagebox.showinfo(\"Result\",\"Capturing screen is completed!!\")\n",
    "    \n",
    "b1=tk.Button(window,text=\"1. Open paint and capture the screen\", font=('Algerian',15),bg=\"orange\",fg=\"black\",command=screen_capture)\n",
    "b1.place(x=5, y=50)\n",
    "\n",
    "def generate_dataset():\n",
    "    import cv2\n",
    "    import csv\n",
    "    import glob\n",
    "\n",
    "    header  =[\"label\"]\n",
    "    for i in range(0,784):\n",
    "        header.append(\"pixel\"+str(i))\n",
    "    with open('dataset.csv', 'a') as f:\n",
    "        writer = csv.writer(f)\n",
    "        writer.writerow(header)\n",
    "\n",
    "    for label in range(10):\n",
    "        dirList = glob.glob(\"captured_images/\"+str(label)+\"/*.png\")\n",
    "\n",
    "        for img_path in dirList:\n",
    "            im= cv2.imread(img_path)\n",
    "            im_gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)\n",
    "            im_gray = cv2.GaussianBlur(im_gray,(15,15), 0)\n",
    "            roi= cv2.resize(im_gray,(28,28), interpolation=cv2.INTER_AREA)\n",
    "\n",
    "            data=[]\n",
    "            data.append(label)\n",
    "            rows, cols = roi.shape\n",
    "\n",
    "            ## Add pixel one by one into data array\n",
    "            for i in range(rows):\n",
    "                for j in range(cols):\n",
    "                    k =roi[i,j]\n",
    "                    if k>100:\n",
    "                        k=1\n",
    "                    else:\n",
    "                        k=0\n",
    "                    data.append(k)\n",
    "            with open('dataset.csv', 'a') as f:\n",
    "                writer = csv.writer(f)\n",
    "                writer.writerow(data)\n",
    "    messagebox.showinfo(\"Result\",\"Generating dataset is completed!!\")\n",
    "    \n",
    "b2=tk.Button(window,text=\"2. Generate dataset\", font=('Algerian',15),bg=\"pink\",fg=\"blue\",command=generate_dataset)\n",
    "b2.place(x=5, y=100)\n",
    "\n",
    "def train_save_accuracy():\n",
    "    import pandas as pd\n",
    "    from sklearn.utils import shuffle\n",
    "    data  =pd.read_csv('dataset.csv')\n",
    "    data=shuffle(data)\n",
    "    X = data.drop([\"label\"],axis=1)\n",
    "    Y= data[\"label\"]\n",
    "    from sklearn.model_selection import train_test_split\n",
    "    train_x,test_x,train_y,test_y = train_test_split(X,Y, test_size = 0.2)\n",
    "    import joblib\n",
    "    from sklearn.svm import SVC\n",
    "    classifier=SVC(kernel=\"linear\", random_state=6)\n",
    "    classifier.fit(train_x,train_y)\n",
    "    joblib.dump(classifier, \"model/digit_recognizer\")\n",
    "    from sklearn import metrics\n",
    "    prediction=classifier.predict(test_x)\n",
    "    acc=metrics.accuracy_score(prediction, test_y)\n",
    "    messagebox.showinfo(\"Result\",f\"Your accuracy is {acc}\")\n",
    "    \n",
    "b3=tk.Button(window,text=\"3. Train the model, save it and calculate accuracy\", font=('Algerian',15),bg=\"green\",fg=\"white\",command=train_save_accuracy)\n",
    "b3.place(x=5, y=150)\n",
    "\n",
    "def prediction():\n",
    "    import joblib\n",
    "    import cv2\n",
    "    import numpy as np #pip install numpy\n",
    "    import time\n",
    "    import pyscreenshot as ImageGrab\n",
    "    import os\n",
    "    os.startfile(\"C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Accessories/Paint\")\n",
    "    \n",
    "    model=joblib.load(\"model/digit_recognizer\")\n",
    "    images_folder=\"img/\"\n",
    "    time.sleep(15)\n",
    "    while True:\n",
    "        img=ImageGrab.grab(bbox=(60,170,400,500))\n",
    "\n",
    "        img.save(images_folder+\"img.png\")\n",
    "        im = cv2.imread(images_folder+\"img.png\")\n",
    "        im_gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)\n",
    "        im_gray  =cv2.GaussianBlur(im_gray, (15,15), 0)\n",
    "\n",
    "        #Threshold the image\n",
    "        ret, im_th = cv2.threshold(im_gray,100, 255, cv2.THRESH_BINARY)\n",
    "        roi = cv2.resize(im_th, (28,28), interpolation  =cv2.INTER_AREA)\n",
    "\n",
    "        rows,cols=roi.shape\n",
    "\n",
    "        X = []\n",
    "\n",
    "        ## Add pixel one by one into data array\n",
    "        for i in range(rows):\n",
    "            for j in range(cols):\n",
    "                k = roi[i,j]\n",
    "                if k>100:\n",
    "                    k=1\n",
    "                else:\n",
    "                    k=0\n",
    "                X.append(k)\n",
    "\n",
    "        predictions  =model.predict([X])\n",
    "        print(\"Prediction:\",predictions[0])\n",
    "        cv2.putText(im, \"Prediction is: \"+str(predictions[0]), (20,20), 0, 0.8,(0,255,0),2,cv2.LINE_AA)\n",
    "\n",
    "        cv2.startWindowThread()\n",
    "        cv2.namedWindow(\"Result\")\n",
    "        cv2.imshow(\"Result\",im)\n",
    "        cv2.waitKey(10000)\n",
    "        if cv2.waitKey(1)==13: #27 is the ascii value of esc, 13 is the ascii value of enter\n",
    "            break\n",
    "    cv2.destroyAllWindows()\n",
    "    \n",
    "b4=tk.Button(window,text=\"4. Live prediction\", font=('Algerian',15),bg=\"white\",fg=\"red\",command=prediction)\n",
    "b4.place(x=5, y=200)\n",
    "\n",
    "window.geometry(\"600x300\")\n",
    "window.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
